title = "Default Config"
last_update = 2022-09-02

[images.magic]
url = "https://github.com/rtimothyedwards/magic"
commit_id = "4afc476d928b138a2d7bd709b52d145cce781394"

[images.skywater-pdk]
url = "https://github.com/google/skywater-pdk.git"
commit_id = "ea95157faad3a3f5c560aaec3f1841ee5a2aa2db"

[images.open_pdks]
url = "https://github.com/RTimothyEdwards/open_pdks"
commit_id = "b8fdad80ab285294461a708cf6a47629f3bbeaff"

[images.netgen]
url = "https://github.com/rtimothyedwards/netgen"
commit_id = "2056b37c95e11ea802f8b06c8948e874a298808a"

[images.ngspice]
url = "https://git.code.sf.net/p/ngspice/ngspice"
commit_id = "0faf386d45521f7ed82f621266b3990adc982b50"

[images.xschem]
url = "https://github.com/StefanSchippers/xschem.git"
commit_id = "b7bf3518019a63395abc33f78a580737f6a50db7"
